---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-int
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 6.6.4
    helm:
      values: |
        ingress:
          enabled: true
          className: cilium
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
          tls:
            - secretName: nextcloud-tls
              hosts:
                - drive.int.k8s.wlankabel.ch
        nextcloud:
          host: drive.int.k8s.wlankabel.ch
          existingSecret:
            enabled: true
            secretName: nextcloud-secret
            usernameKey: nextcloud-admin-username
            passwordKey: nextcloud-admin-password
          containerPort: 80
          phpClientHttpsFix:
            enabled: true
            protocol: https
        persistence:
          enabled: true
          storageClass: lh-ssd-r2
          accessMode: ReadWriteOnce
          size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: s-nextcloud-int
